from tkinter import *
root=Tk()
root.title("simple calculator")
root.geometry("500x700")

def click():
    a=int(e1.get())
    b=int(e2.get())
    add=a+b
    sub=a-b
    mul=a*b
    div=a/b
    mod=a%b
    e3.delete(0,END)
    e3.insert(0,str(add))
    e4.delete(0,END)
    e4.insert(0,str(sub))
    e5.delete(0,END)
    e5.insert(0,str(mul))
    e6.delete(0,END)
    e6.insert(0,str(div))
    e7.delete(0,END)
    e7.insert(0,str(mod))
    return

f1=Frame(root)
f1.config(bg="BLACK")
f1.pack(fill="both",expand=0)
l1=Label(f1,text="ARITHMETIC OPERATION",bg="ORANGE",fg="BLACK",font=("Arial",18,"bold"))
l1.pack()
f2=Frame(root)
f2.config(bg="VIOLET")
f2.pack(fill="both",expand=0)
l2=Label(f2,text="Enter the First Number")
l2.pack()
e1=Entry(f2)
e1.pack()
l3=Label(f2,text="Enter the Second Number")
l3.pack()
e2=Entry(f2)
e2.pack()
l4=Label(f2,text="Addition")
l4.pack()
e3=Entry(f2)
e3.pack()
l5=Label(f2,text="Subtraction")
l5.pack()
e4=Entry(f2)
e4.pack()
l6=Label(f2,text="Multiplication")
l6.pack()
e5=Entry(f2)
e5.pack()
l7=Label(f2,text="Division")
l7.pack()
e6=Entry(f2)
e6.pack()
l8=Label(f2,text="Modules")
l8.pack()
e7=Entry(f2)
e7.pack()
b1=Button(f2,text="Click",command=click)
b1.pack()
root.mainloop()
